# fly.toml app configuration file generated for etf-service
# See https://fly.io/docs/reference/configuration/ for details.

app = "etf-service"
primary_region = "fra"

[build]

[processes]
  app = "node core/server.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"      # NON spegnere la macchina
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512MB"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
