# fly.toml app configuration file generated for etf-service on 2025-12-20T17:56:53Z

app = 'etf-service'
primary_region = 'fra'

[build]

[processes]
  app = "node core/server.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'      # NON spegnere la macchina
  auto_start_machines = true
  min_machines_running = 1        # Tieni almeno 1 macchina sempre accesa
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
