
# fly.toml app configuration file generated for etf-service on 2025-12-20T17:56:53Z

app = 'etf-service'
primary_region = 'fra'

[build]

[processes]
  app = "node core/server.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# JOB 21-UTC — lo script decide se è l'ora giusta (23:00 italiane)
[[jobs]]
  processes = ["app"]
  name = "save-previous-close-21utc"
  schedule = "0 21 * * 1-5"
  command = ["node", "scripts/savePreviousClose.js"]

[[jobs]]
  processes = ["app"]
  name = "save-previous-close-22utc"
  schedule = "0 22 * * 1-5"
  command = ["node", "scripts/savePreviousClose.js"]
